apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
spec:
  project: platform
  source:
    parth: Platforms
    repoURL: https://github.com/danielndias/AppOfApps.git
    targetRevision: HEAD
  destination:
    server: in-cluster
    namespace: argo-cd