apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
spec:
  destination:
    namespace: argo-cd
    server: https://kubernetes.default.svc
  source:
    path: 'Platforms'
    repoURL: git@github.com:danielndias/AppOfApps.git
    targetRevision: HEAD
    parth: Platforms
  sources: []
  project: platform
