apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare
  namespace: argocd
spec:
  project: platform
  sources:
    - chart: cloudflare
      repoURL: https://cloudflare.github.io/helm-charts
      targetRevision: 0.3.2
      helm:
        valueFiles:
          - $cloudflare/tunnel-values.yaml
    - repoURL: git@github.com:danielndias/homelab-platform.git
      targetRevision: HEAD
      ref: cloudflare
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cloudflare
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true