apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-smb
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: git@github.com:danielndias/homelab-platform.git
    targetRevision: HEAD
    path: csi-smb
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system