# yaml-language-server: $schema=https://json.schemastore.org/yamllint.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metal-lb
  namespace: argocd
spec:
  project: platform
  source:
    chart: metallb
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.14.9
    helm:
      releaseName: metallb
  destination:
    server: "https://kubernetes.default.svc"
    namespace: metallb-system