apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard-secondary
  namespace: argocd
spec:
  project: services
  source:
    repoURL: git@github.com:danielndias/homelab.git
    targetRevision: HEAD
    path: Services/adguard-secondary
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true