apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: audiobookshelf
  namespace: argocd
spec:
  project: apps
  source:
    repoURL: git@github.com:danielndias/homelab.git
    targetRevision: HEAD
    path: Apps/audiobookshelf
  destination:
    server: "https://kubernetes.default.svc"
    namespace: audiobookshelf
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true