# yaml-language-server: $schema=https://json.schemastore.org/yamllint.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calibre
  namespace: argocd
spec:
  project: apps
  source:
    repoURL: git@github.com:danielndias/homelab.git
    targetRevision: HEAD
    path: Apps/calibre
  destination:
    server: "https://kubernetes.default.svc"
    namespace: calibre
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true